# Generated by Django 5.0.7 on 2024-08-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_commentlike_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='Is modified'),
        ),
    ]
