# Generated by Django 5.0.7 on 2024-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='user.png', upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
