# Generated by Django 5.0.7 on 2024-08-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        ('users', '0003_alter_profile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='search.tag'),
        ),
    ]
