# Generated by Django 5.0.7 on 2024-08-02 13:57

import django.db.models.deletion
import django.utils.timezone
import medias.business
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Text')),
                ('media', models.FileField(upload_to='media_files/%Y/%m/%d', validators=[medias.business.media_file_validator, medias.business.file_size], verbose_name='Media')),
                ('original', models.FileField(blank=True, null=True, upload_to='original_files/%Y/%m/%d', validators=[medias.business.original_file_validator, medias.business.file_size], verbose_name='Original')),
                ('slug', models.SlugField(blank=True, max_length=10, verbose_name='Slug')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Downloads count')),
                ('tags', models.ManyToManyField(blank=True, related_name='medias', to='search.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'medias',
            },
        ),
        migrations.CreateModel(
            name='MediaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='medias.media')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'view',
                'verbose_name_plural': 'views',
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='medias.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'unique_together': {('media', 'user')},
            },
        ),
    ]
